import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F0F0F0"
  },
  textheader: {
    fontSize: 15,
    marginBottom: 5,
    marginLeft: 9
  },
  textInput: {
    borderRadius: 10,
    borderWidth: 1,
    height: 44,
    backgroundColor: '#F9F9f9',
    color: '#000000',
    borderColor: '#000000',
    borderBottomWidth: 1,
    marginBottom: 16,
    paddingHorizontal: 12,
    textAlignVertical: 'center',
  },
  fab: {
    position: 'absolute',
    right: 24,
    bottom: 32,
    backgroundColor: '#4CAF50',
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 8,
    shadowColor: '#4CAF50',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    zIndex: 10,
  },
  modalContent: {
    width: 340,
    maxWidth: 480,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    elevation: 10,
    alignSelf: 'center',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 4,
    color: '#222',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollViewContainer: {
    padding: 5,
  },
  listCardContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 10,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
    marginHorizontal:5
  },
  cardContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 16,
    flexWrap: 'wrap',
    gap: 8,
  },
  labelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 5,
  },

  textTitleViewCourse: {
    fontWeight: 'bold',
    color: '#222',
    fontSize: 16,
  },
  textSubtitleViewCourse: {
    color: '#555',
    fontSize: 13,
    marginBottom: 2,
  },
  labelText: {
    width: 100,
    color: '#555',
    fontSize: 13,
    marginBottom: 2,
  },

  valueText: {
    flex: 1,
    color: '#555',
    fontSize: 13,
    marginBottom: 2,
  },
  editDetails: {
    marginRight: 8,
    margin: 10
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    marginTop: 12,
  },
  primaryButton: {
    backgroundColor: '#4CAF50',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  secondaryButton: {
    backgroundColor: '#eee',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  buttonTextPrimary: {
    color: '#fff',
    fontWeight: '600',
  },
  buttonTextSecondary: {
    color: '#222',
    fontWeight: '600',
  },
  dateselection: {
    paddingVertical: 10,
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 10,
    padding: 10,
    marginBottom: 5,
    width: '100%',
    height: 44,
  },
  percentBar: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 10,
    marginHorizontal:10,
    elevation: 2,
    flexDirection: 'row',
    alignContent: 'center',
    justifyContent: 'space-evenly',
    margin: 5
  },
  ClearFilterView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginBottom: 10,
    marginHorizontal:20,
  },
  ClearFilter: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#f3f4f6',
    borderRadius: 6,
  },
  ClearFilterText: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '500',
    marginTop: 5
  },
  FilterModuleOpen: {
    backgroundColor: '#f3f4f6',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  FilterText: {
    color: '#374151',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 4,
  },
  showFilterModule: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 999,
  },
  FilterModuleView: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    padding: 16,
    zIndex: 1000,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 8,
  },
  FiltersView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  FiltersOpen: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#222',
  },
  categoryText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 8,
  },
  percentshow: {
    height: 12,
    borderColor: "#000000",
    borderWidth: 1,
    borderRadius: 8,
    overflow: 'hidden',
    marginBottom: 5,
    marginHorizontal: 20
  },
  percentCard: {
    borderRadius: 12,
    padding: 2,
    marginHorizontal: 10,
    elevation: 2,
    margin: 5,
  }
});
